/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dlocal_NewRelicJNI */

#ifndef _Included_com_dlocal_NewRelicJNI
#define _Included_com_dlocal_NewRelicJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dlocal_NewRelicJNI
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dlocal_NewRelicJNI_init
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_dlocal_NewRelicJNI
 * Method:    startWebTransaction
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dlocal_NewRelicJNI_startWebTransaction
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_dlocal_NewRelicJNI
 * Method:    endWebTransaction
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dlocal_NewRelicJNI_endWebTransaction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dlocal_NewRelicJNI
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dlocal_NewRelicJNI_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
