FROM adoptopenjdk/openjdk11:ubi
COPY ./c-sdk .

RUN yum update 
RUN yum -y install bash

RUN yum -y install git
RUN yum -y install pcre gcc gcc-c++ make pcre-devel
RUN yum -y install go


RUN go env -w GO111MODULE=auto
RUN make

RUN gcc -fPIC -Wall -shared -o newrelicjni.so newrelicjni.c -I $JAVA_HOME/include -I $JAVA_HOME/include/linux -I ./include -L. -lnewrelic -lpcre -lpthread -lm -rdynamic

CMD cp newrelicjni.so shared/newrelicjni.so.ubi